#include "deque/deque.h"
#include "deque/dequeUnitTests.h"
#include "queue/queue.h"
#include "queue/queueUnitTests.h"
#include "segmentedDeque/segmentedDeque.h"
#include "stack/stack.h"
#include "stack/stackUnitTests.h"